version: '3'
services:
  backend:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo
  
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
  
  mongo:
    image: mongo
    ports:
      - "27017:27107"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: